### ISSUE TITLE
Automatically or manually 'retest' domains from a scan in case of test errors

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#370] opened 2022-05-19 10:49 UTC
Scans sometimes contain test errors. These can be temporary (one off) errors, or persistent errors. In case of temporary errors, it would be useful if the system automatically retries (retests) these domains, and updates the results within a certain timeframe, or if individual domains can be manually retested (multi or single retest).

An option would be to make this a 'Setting' of a list -> retest errors within a time span of 1 hour, 1 day or x days after the initial scan. The report should not be generated until the retesting is complete.
Ofcourse persistent errors will remain erronous in the final report.

Another option would be a "retest button" (or multiple domain selection and single 'multi retest' button)  next to all individual test results in a report. Pushing that button would then overwrite the old results for that domain. The graphs would then also have to be updated to reflect changes. (I guess that means the whole report has to be overwritten?)

![image](https://user-images.githubusercontent.com/28256969/169275007-49c8b068-1883-4357-b516-76b6d202852b.png)

**Comment by WKobes** [comment] 2022-12-06 13:39
Duplicate of #278

**Closed by WKobes** 2022-12-06 13:39 UTC
Labels: enhancement
