### ISSUE TITLE
Dynamic averages check boxes

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#66] opened 2019-07-31 19:36 UTC
![afbeelding](https://user-images.githubusercontent.com/28256969/62242269-100ce100-b3db-11e9-9310-ef3ac262c604.png)
Maybe this many 'dynamic averages' check boxes is a bit too much.

Perhaps simplify this by only showing the red circled check boxes?

**Comment by stitch** [comment] 2019-10-10 12:07
Duplicate of #6

**Closed by stitch** 2019-10-10 12:07 UTC
Labels: enhancement
