### ISSUE TITLE
Visualize changes on individual test results in recurring reports

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#84] opened 2019-09-13 12:52 UTC
When recurringly measuring a set of domains, its useful to visualize whether an individual test result is better or worse than the previous measurement by showing a green arrow up (better) or red arrow down (worse).

**Comment by stitch** [comment] 2019-10-10 13:53
Duplicate of #74

**Closed by stitch** 2019-10-10 13:53 UTC
