### ISSUE TITLE
Update DNS Resolver list

### ISSUE THREAD

**Issue by bwbroersma** [internetstandards/Internet.nl-dashboard#418] opened 2023-04-18 15:48 UTC
Currently using #250:
CZ.NIC:
["193.17.47.1", "185.43.135.1",

UncencoredDNS:
"130.225.244.166"]

Add some IPv6, add more (stable) DNS resolvers.
Also see https://european-alternatives.eu/category/public-dns

**Comment by bwbroersma** [comment] 2023-05-04 16:19
I found a different list in the public config than noted in #250 running in production:
https://github.com/internetstandards/Internet.nl-dashboard/blob/6e5d18e914c66c074cb185aff8fc8b9686c18e56/dashboard/settings.py#L512

@stitch Do we have DoH / DoT support for the resolving nameservers? Because if 130.225.244.166 is currently used as one of the three resolving nameserver and the dashboard backend expects plain port 53 DNS, then 1/3 of all lookups would currently fail. See https://blog.uncensoreddns.org/blog/40-cleartext-dns-turned-off/

Note that UncencoredDNS also states [on the page](https://blog.uncensoreddns.org/dns-servers/) "Listens on port 853 for DoT and on port 443 for DoH.". It would be nice to add some DNS resolver IP addresses that are anycast.

---
Some checking of the nameservers:
BTW pretty hard to transform this text back to a plain text list again 😅
```bash
xsel | sed -r -n 's/.*\b(([0-9]{1,3}\.){3}[0-9]{1,3})\b.*/\1/gp'
```
- 193.17.47.1
- 185.43.135.1
- 91.239.100.100
- 193.110.81.0
- 185.253.5.0
- 9.9.9.9
- 149.112.112.112

```bash
xsel -b | sed -r -n 's/(^|.*[^0-9a-fA-F:])(([0-9a-fA-F]{1,4}::?)+[0-9a-fA-F]{1,4}(::)?)($|[^0-9a-fA-F:])/\2/gp'
```
- 2001:148f:ffff::1
- 2001:148f:fffe::1
- 2001:67c:28a4::
- 2a0f:fc80::
- 2a0f:fc81::
- 2620:fe::fe
- 2620:fe::9

Doing a plain port 53 lookup test (with 1 try and 1s timeout):
```bash
xsel | xargs -n1 bash -c 'echo -en "Resolver $0:\t";dig +tries=1 +timeout=1 @$0 internet.nl +short +dnssec | tr "\n" ";";echo'
```
Results in:
```none
Resolver 193.17.47.1:	62.204.66.10;A 13 2 3600 20230513043745 20230429043238 22707 internet.nl. uCfzm7jFTk7bC2Wesa6zYvXP1CoqtUwpOEe7dNNL7Mv8TKThDnNw27nb ir2Bdon11OI/IcrNJuJBaTG0/854vQ==;
Resolver 185.43.135.1:	62.204.66.10;A 13 2 3600 20230513043745 20230429043238 22707 internet.nl. uCfzm7jFTk7bC2Wesa6zYvXP1CoqtUwpOEe7dNNL7Mv8TKThDnNw27nb ir2Bdon11OI/IcrNJuJBaTG0/854vQ==;
Resolver 91.239.100.100:	;; <<>> DiG 9.16.37-Debian <<>> +tries +timeout @91.239.100.100 internet.nl +short +dnssec;; (1 server found);;; global options: +cmd;;; connection timed out; no servers could be reached;;
Resolver 193.110.81.0:	62.204.66.10;A 13 2 3600 20230513043745 20230429043238 22707 internet.nl. uCfzm7jFTk7bC2Wesa6zYvXP1CoqtUwpOEe7dNNL7Mv8TKThDnNw27nb ir2Bdon11OI/IcrNJuJBaTG0/854vQ==;
Resolver 185.253.5.0:	62.204.66.10;A 13 2 3600 20230513043745 20230429043238 22707 internet.nl. uCfzm7jFTk7bC2Wesa6zYvXP1CoqtUwpOEe7dNNL7Mv8TKThDnNw27nb ir2Bdon11OI/IcrNJuJBaTG0/854vQ==;
Resolver 9.9.9.9:	62.204.66.10;A 13 2 3600 20230513043745 20230429043238 22707 internet.nl. uCfzm7jFTk7bC2Wesa6zYvXP1CoqtUwpOEe7dNNL7Mv8TKThDnNw27nb ir2Bdon11OI/IcrNJuJBaTG0/854vQ==;
Resolver 149.112.112.112:	62.204.66.10;A 13 2 3600 20230513043745 20230429043238 22707 internet.nl. uCfzm7jFTk7bC2Wesa6zYvXP1CoqtUwpOEe7dNNL7Mv8TKThDnNw27nb ir2Bdon11OI/IcrNJuJBaTG0/854vQ==;
Resolver 2001:148f:ffff::1:	62.204.66.10;A 13 2 3600 20230513043745 20230429043238 22707 internet.nl. uCfzm7jFTk7bC2Wesa6zYvXP1CoqtUwpOEe7dNNL7Mv8TKThDnNw27nb ir2Bdon11OI/IcrNJuJBaTG0/854vQ==;
Resolver 2001:148f:fffe::1:	62.204.66.10;A 13 2 3600 20230513043745 20230429043238 22707 internet.nl. uCfzm7jFTk7bC2Wesa6zYvXP1CoqtUwpOEe7dNNL7Mv8TKThDnNw27nb ir2Bdon11OI/IcrNJuJBaTG0/854vQ==;
Resolver 2001:67c:28a4:::	;; <<>> DiG 9.11.5-P4-5.1+deb10u8-Debian <<>> +tries=1 +timeout=1 @2001:67c:28a4:: internet.nl +short +dnssec;; (1 server found);;; global options: +cmd;;; connection timed out; no servers could be reached;
Resolver 2a0f:fc80:::	62.204.66.10;A 13 2 3600 20230513043745 20230429043238 22707 internet.nl. uCfzm7jFTk7bC2Wesa6zYvXP1CoqtUwpOEe7dNNL7Mv8TKThDnNw27nb ir2Bdon11OI/IcrNJuJBaTG0/854vQ==;
Resolver 2a0f:fc81:::	62.204.66.10;A 13 2 3600 20230513043745 20230429043238 22707 internet.nl. uCfzm7jFTk7bC2Wesa6zYvXP1CoqtUwpOEe7dNNL7Mv8TKThDnNw27nb ir2Bdon11OI/IcrNJuJBaTG0/854vQ==;
Resolver 2620:fe::fe:	62.204.66.10;A 13 2 3600 20230513043745 20230429043238 22707 internet.nl. uCfzm7jFTk7bC2Wesa6zYvXP1CoqtUwpOEe7dNNL7Mv8TKThDnNw27nb ir2Bdon11OI/IcrNJuJBaTG0/854vQ==;
Resolver 2620:fe::9:	62.204.66.10;A 13 2 3600 20230513043745 20230429043238 22707 internet.nl. uCfzm7jFTk7bC2Wesa6zYvXP1CoqtUwpOEe7dNNL7Mv8TKThDnNw27nb ir2Bdon11OI/IcrNJuJBaTG0/854vQ==;
```

**Comment by stitch** [comment] 2023-05-11 07:17
> @stitch Do we have DoH / DoT support for the resolving nameservers? Because if 130.225.244.166 is currently used as one of the three resolving nameserver and the dashboard backend expects plain port 53 DNS, then 1/3 of all lookups would currently fail. See https://blog.uncensoreddns.org/blog/40-cleartext-dns-turned-off/
> 
> Note that UncencoredDNS also states [on the page](https://blog.uncensoreddns.org/dns-servers/) "Listens on port 853 for DoT and on port 443 for DoH.". It would be nice to add some DNS resolver IP addresses that are anycast.

Confirmed, "dns.resolver.LifetimeTimeout: The resolution lifetime expired after 5.402 seconds: Server 130.225.244.166 UDP port 53 answered The DNS operation timed out.; Server 130.225.244.166 UDP port 53 answered The DNS operation timed out.; Server 130.225.244.166 UDP port 53 answered The DNS operation timed out."

When a resolver-address doesn't resolve, the next address is used. As we use 3, it has not turned out to be a problem. Due to the timeouts resolving has been slower than needed.

**Comment by bwbroersma** [comment] 2023-05-11 07:50
@stitch Why do we have a different list in the public config than running in production? (as noted in #250)
https://github.com/internetstandards/Internet.nl-dashboard/blob/6e5d18e914c66c074cb185aff8fc8b9686c18e56/dashboard/settings.py#L512

Shouldn't we keep it in sync?

**Comment by stitch** [comment] 2023-05-16 07:34
todo: update defaults as well

**Comment by stitch** [comment] 2023-05-17 12:40
Added, included a tool that allows for checking DNS resolving:

'dashboard check_dns_resolvers` which uses data from CONNECTIVITY_TEST_DOMAIN and SCANNER_NAMESERVERS.

**Closed by stitch** 2023-05-17 12:40 UTC
