### ISSUE TITLE
Report doesn't load when opening from direct link 

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#369] opened 2022-05-19 10:38 UTC
If I open a link like https://acc.dashboard.internet.nl/#/report/695 it will not load the report directly. I still have to select it from the dropdown list.
Also happens when you click "Open report" from the Scans page.

**Comment by WKobes** [comment] 2022-12-06 13:32
Duplicate of #337

**Closed by WKobes** 2022-12-06 13:32 UTC
Labels: bug
