### ISSUE TITLE
Date of report is a day later than the real date

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#75] opened 2019-08-30 20:39 UTC
When I run a test, the date that is displayed on the test and the diagrams is wrong.

Example: https://acc.dashboard.internet.nl/reports/82/

I ran the test on the 30th:
![afbeelding](https://user-images.githubusercontent.com/28256969/64049941-dc0e1280-cb76-11e9-8483-5877a0fa0266.png)

But the diagrams show the 31st as the date:
![afbeelding](https://user-images.githubusercontent.com/28256969/64049974-f9db7780-cb76-11e9-93da-8a8d1b05e2c2.png)

**Comment by robinbzk** [comment] 2019-08-30 20:52
Besides the above, the report title is different when opening the report from "Scans" or from the "Rapporten" page.

![afbeelding](https://user-images.githubusercontent.com/28256969/64050556-b5e97200-cb78-11e9-88a2-1b333ef44f57.png)

![afbeelding](https://user-images.githubusercontent.com/28256969/64050594-d87b8b00-cb78-11e9-9c1b-db6da3503389.png)

**Comment by stitch** [comment] 2019-09-13 11:59
quick fix: only show date, on same day.

**Comment by stitch** [comment] 2019-10-10 13:14
This is largely due to #5. Some trickery can be applied reducing 2 hours, but the root cause of the issue would not be addressed yet.

**Comment by stitch** [comment] 2019-11-19 13:53
Reduced by 2 hours, will be fixed for real later on.

**Closed by stitch** 2019-11-19 13:53 UTC
